# -*- coding: utf-8 -*-
"""pr10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vJsL67e0341YruE7ZcHP4fZhqL96ELiW
"""

import numpy as np
import pandas as pd
import os

titanic_train=pd.read_csv("/content/train.csv")

titanic_train.shape

titanic_train.dtypes

titanic_train.head()

titanic_train.describe()

titanic_train

del titanic_train['Pclass']

titanic_train.dtypes

sorted (titanic_train["Name"])[0:15]

titanic_train["Name"].describe()

new_survived = pd.Categorical(titanic_train["Survived"])

new_survived

new_survived = new_survived.rename_categories(["Died","Survived"])

new_survived

titanic_train["Age"].describe()

missing = np.where(titanic_train["Age"].isnull() == True)
missing

len(missing[0])

titanic_train.hist(column='Age',    # Column to plot
                   figsize=(9,6),   # Plot size
                   bins=20)         # Number of histogram bins

titanic_train['Age'] = titanic_train['Age'].fillna(titanic_train['Age'].mean())

missing = np.where(titanic_train["Age"].isnull() == True)
missing

titanic_train.head(10)