# -*- coding: utf-8 -*-
"""pr7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SnXerLvoRzqkblJpc5uBQmnm4ZGNZWQn
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB

df=pd.read_csv('/content/playsheet_dataset.csv')
df

Numerics=LabelEncoder()

inputs=df.drop('Play',axis='columns')
target=df['Play']
target

inputs['outlook_n']=Numerics.fit_transform(inputs['Outlook'])
inputs['Temp_n']=Numerics.fit_transform(inputs['Temp'])
inputs['Humidity_n']=Numerics.fit_transform(inputs['Humidity'])
inputs['windy_n']=Numerics.fit_transform(inputs['Windy'])
inputs

inputs_n=inputs.drop(['Outlook','Temp','Humidity','Windy'],axis='columns')
inputs_n

Classifier=GaussianNB()
Classifier.fit(inputs_n,target)



Classifier.score(inputs_n,target)

Classifier.predict([[0,0,0,1]])